/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TribesRouteImport } from './routes/tribes'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PicsRouteImport } from './routes/pics'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as MoonsRouteImport } from './routes/moons'
import { Route as MapRouteImport } from './routes/map'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AbilitiesRouteImport } from './routes/abilities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TribesSlugRouteImport } from './routes/tribes.$slug'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'

const TribesRoute = TribesRouteImport.update({
  id: '/tribes',
  path: '/tribes',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PicsRoute = PicsRouteImport.update({
  id: '/pics',
  path: '/pics',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonsRoute = MoonsRouteImport.update({
  id: '/moons',
  path: '/moons',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AbilitiesRoute = AbilitiesRouteImport.update({
  id: '/abilities',
  path: '/abilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TribesSlugRoute = TribesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TribesRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/builder': typeof BuilderRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRouteWithChildren
  '/facts': typeof FactsRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/moons': typeof MoonsRoute
  '/parents': typeof ParentsRoute
  '/pics': typeof PicsRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/tribes': typeof TribesRouteWithChildren
  '/characters/$slug': typeof CharactersSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/builder': typeof BuilderRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRouteWithChildren
  '/facts': typeof FactsRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/moons': typeof MoonsRoute
  '/parents': typeof ParentsRoute
  '/pics': typeof PicsRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/tribes': typeof TribesRouteWithChildren
  '/characters/$slug': typeof CharactersSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/builder': typeof BuilderRoute
  '/cards': typeof CardsRoute
  '/characters': typeof CharactersRouteWithChildren
  '/facts': typeof FactsRoute
  '/journal': typeof JournalRoute
  '/map': typeof MapRoute
  '/moons': typeof MoonsRoute
  '/parents': typeof ParentsRoute
  '/pics': typeof PicsRoute
  '/quiz': typeof QuizRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/tribes': typeof TribesRouteWithChildren
  '/characters/$slug': typeof CharactersSlugRoute
  '/tribes/$slug': typeof TribesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abilities'
    | '/academy'
    | '/achievements'
    | '/builder'
    | '/cards'
    | '/characters'
    | '/facts'
    | '/journal'
    | '/map'
    | '/moons'
    | '/parents'
    | '/pics'
    | '/quiz'
    | '/sitemap.xml'
    | '/story'
    | '/tribes'
    | '/characters/$slug'
    | '/tribes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abilities'
    | '/academy'
    | '/achievements'
    | '/builder'
    | '/cards'
    | '/characters'
    | '/facts'
    | '/journal'
    | '/map'
    | '/moons'
    | '/parents'
    | '/pics'
    | '/quiz'
    | '/sitemap.xml'
    | '/story'
    | '/tribes'
    | '/characters/$slug'
    | '/tribes/$slug'
  id:
    | '__root__'
    | '/'
    | '/abilities'
    | '/academy'
    | '/achievements'
    | '/builder'
    | '/cards'
    | '/characters'
    | '/facts'
    | '/journal'
    | '/map'
    | '/moons'
    | '/parents'
    | '/pics'
    | '/quiz'
    | '/sitemap.xml'
    | '/story'
    | '/tribes'
    | '/characters/$slug'
    | '/tribes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbilitiesRoute: typeof AbilitiesRoute
  AcademyRoute: typeof AcademyRoute
  AchievementsRoute: typeof AchievementsRoute
  BuilderRoute: typeof BuilderRoute
  CardsRoute: typeof CardsRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  FactsRoute: typeof FactsRoute
  JournalRoute: typeof JournalRoute
  MapRoute: typeof MapRoute
  MoonsRoute: typeof MoonsRoute
  ParentsRoute: typeof ParentsRoute
  PicsRoute: typeof PicsRoute
  QuizRoute: typeof QuizRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  TribesRoute: typeof TribesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tribes': {
      id: '/tribes'
      path: '/tribes'
      fullPath: '/tribes'
      preLoaderRoute: typeof TribesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pics': {
      id: '/pics'
      path: '/pics'
      fullPath: '/pics'
      preLoaderRoute: typeof PicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moons': {
      id: '/moons'
      path: '/moons'
      fullPath: '/moons'
      preLoaderRoute: typeof MoonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abilities': {
      id: '/abilities'
      path: '/abilities'
      fullPath: '/abilities'
      preLoaderRoute: typeof AbilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribes/$slug': {
      id: '/tribes/$slug'
      path: '/$slug'
      fullPath: '/tribes/$slug'
      preLoaderRoute: typeof TribesSlugRouteImport
      parentRoute: typeof TribesRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface CharactersRouteChildren {
  CharactersSlugRoute: typeof CharactersSlugRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersSlugRoute: CharactersSlugRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface TribesRouteChildren {
  TribesSlugRoute: typeof TribesSlugRoute
}

const TribesRouteChildren: TribesRouteChildren = {
  TribesSlugRoute: TribesSlugRoute,
}

const TribesRouteWithChildren =
  TribesRoute._addFileChildren(TribesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbilitiesRoute: AbilitiesRoute,
  AcademyRoute: AcademyRoute,
  AchievementsRoute: AchievementsRoute,
  BuilderRoute: BuilderRoute,
  CardsRoute: CardsRoute,
  CharactersRoute: CharactersRouteWithChildren,
  FactsRoute: FactsRoute,
  JournalRoute: JournalRoute,
  MapRoute: MapRoute,
  MoonsRoute: MoonsRoute,
  ParentsRoute: ParentsRoute,
  PicsRoute: PicsRoute,
  QuizRoute: QuizRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  TribesRoute: TribesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
